os:
  - linux
  - osx
arch:
  - amd64
  - ppc64le
language: C

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
  allow_failures:
    - os: osx

dist: xenial

addons:
  apt:
    packages:
      - libxml2-dev
      - libglib2.0-dev
      - intltool
      - gtk-doc-tools
      - libusb-1.0-0-dev
      - libaudit-dev
      - ninja-build
      - python3-pip
      - python3-dev
      - gobject-introspection
      - valgrind
    update: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja intltool valgrind; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force gettext ; fi
  - sudo pip3 install --upgrade setuptools pip
  - sudo pip3 install 'meson==0.47'

script:
  - meson build
  - cd build
  - meson configure
  - ninja
  - meson test --no-suite="network"
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then meson test --suite="network" ; fi
  - if [[ "$TRAVIS_CPU_ARCH" != "ppc64le" ]]; then ../tests/valgrind-memcheck --no-suite="network"; fi
  - if [[ "$TRAVIS_CPU_ARCH" != "ppc64le" && "$TRAVIS_OS_NAME" != "osx" ]]; then ../tests/valgrind-memcheck --suite="network" ; fi
